apiVersion: apps/v1
kind: Deployment
metadata:
  name: loomi-api
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: loomi-api
  template:
    metadata:
      labels:
        app: loomi-api
    spec:
      containers:
      - name: loomi-api
        image: DOCKER_IMAGE
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-credentials 
              key: DATABASE_URL
        ports:
        - containerPort: 8000
