apiVersion: apps/v1
kind: Deployment
metadata:
  name: loomi-api
  annotations:
    kubernetes.io/change-cause: "Updated deployment with probes and resource limits"
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1   
  selector:
    matchLabels:
      app: loomi-api
  template:
    metadata:
      labels:
        app: loomi-api
      annotations:
        rollme: "v2" 
    spec:
      containers:
      - name: loomi-api
        image: 063674011189.dkr.ecr.us-east-1.amazonaws.com/infra/loomi-api
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DATABASE_URL
        ports:
        - containerPort: 8000
        # livenessProbe:
        #   httpGet:
        #     path: /healthz
        #     port: 8000
        #   initialDelaySeconds: 10
        #   periodSeconds: 5
        #   timeoutSeconds: 3
        #   failureThreshold: 3
        # readinessProbe:
        #   httpGet:
        #     path: /readiness
        #     port: 8000
        #   initialDelaySeconds: 5
        #   periodSeconds: 5
        #   timeoutSeconds: 3
        #   failureThreshold: 3
      imagePullSecrets:
      - name: ecr-registry-secret
