apiVersion: apps/v1
kind: Deployment
metadata:
  name: loomi-api
  annotations:
    kubernetes.io/change-cause: "Testing rolling update strategy - v1"
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: loomi-api
  template:
    metadata:
      labels:
        app: loomi-api
    spec:
      containers:
      - name: loomi-api
        image: 063674011189.dkr.ecr.us-east-1.amazonaws.com/infra/loomi-api
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DATABASE_URL
        ports:
        - containerPort: 8000
      imagePullSecrets:
      - name: ecr-registry-secret
