name: Deploy to EKS
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
  IMAGE_TAG: ${{ github.sha }}
  EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}
  AWS_REGION: us-east-1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Run tests
        run: |
          echo "Running tests..."

  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update kube config
        run: |
          aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION
          kubectl config current-context

      - name: Deploy to EKS
        run: |
          # Update image tag in deployment
          sed -i "s|063674011189.dkr.ecr.us-east-1.amazonaws.com/infra/loomi-api|$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG|" EKS/deployment.yaml
          
          # Apply configurations
          kubectl apply -f EKS/deployment.yaml
          kubectl apply -f EKS/service.yaml
          
          # Wait for rollout
          kubectl rollout status deployment/loomi-api

      - name: Verify deployment
        run: |
          kubectl get pods -l app=loomi-api
